Sales_accounting/Sales_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('account/', include('account.urls')),
]

Sales_accounting/sales/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.sales_list, name='sales_list'),
    path('create/', views.sale_create, name='sale_create'),
    path('delete/<int:id>', views.sale_delete, name='sale_delete'),

]

Sales_accounting/sales/models.py
from django.db import models
from products.models import Product
from django.core.exceptions import ValidationError
from account.models import Profile


class Sale(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    final_price = models.IntegerField()
    buyer = models.ForeignKey('counterparties.Counterparty', on_delete=models.CASCADE, related_name='sales', null=True)
    created_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sales', null=True)

Sales_accounting/sales/forms.py
from django import forms
from .models import Sale
from django.forms import ValidationError


class SaleCreateForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['product', 'amount', 'buyer']

        widgets = {
            'product': forms.Select(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'buyer': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        product = self.cleaned_data['product']
        if amount > product.amount:
            raise ValidationError('Too much amount!')
        return amount

    def clean_buyer(self):
        buyer = self.cleaned_data['buyer']
        if buyer.type != 'buyer':
            raise ValidationError('Please choose buyer counteragent')
        return buyer

Sales_accounting/sales/views.py
from django.shortcuts import render, redirect
from .forms import SaleCreateForm
from .models import Sale
from products.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def sales_list(request):
    sales = Sale.objects.filter(created_user=request.user.profile)
    return render(request, 'sales/sales_list.html', {'sales': sales, 'section': 'sales'})


def sale_create(request):
    if request.method == 'POST':
        form = SaleCreateForm(request.POST)
        if form.is_valid():
            new_sale = form.save(commit=False)
            new_sale.final_price = new_sale.product.price * new_sale.amount
            new_sale.created_user = request.user.profile
            new_sale.save()
            current_product = Product.objects.get(id=new_sale.product.id)
            current_product.amount -= new_sale.amount
            current_product.save()
        return render(request, 'sales/sale_create.html', {'form': form})
    else:
        form = SaleCreateForm()
        return render(request, 'sales/sale_create.html', {'form': form})


def sale_delete(request, id):
    sale_for_delete = Sale.objects.get(id=id)
    sale_for_delete.delete()
    messages.error(request, 'Sale deleted successfully')
    return redirect('sales:sales_list')

Sales_accounting/sales/templates/sales/sale_create.html
{% extends 'base.html' %}

{% block title %}
    Sale
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

Sales_accounting/sales/templates/sales/sales_list.html
{% extends 'base.html' %}

{% block title %}
    Sales
{% endblock %}

{% block content %}

    <p>
        <header>
            <a class="button" href="{% url 'sales:sale_create' %}">Add new sale</a>
        </header>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Время</th>
            <th scope="col">Продукт</th>
            <th scope="col">Количество</th>
            <th scope="col">Итоговая цена</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for sale in sales %}
            <tr>
                <th scope="row">{{ sale.id }}</th>
                <th scope="row">{{ sale.time }}</th>
                <th scope="row">{{ sale.product.name }}</th>
                <th scope="row">{{ sale.amount }}</th>
                <th scope="row">{{ sale.final_price }}</th>
                <td scope="col"><a class="button-danger"
                                   href="{% url 'sales:sale_delete' sale.id %}">DELETE</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}