Sales_accounting/Sales_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('account/', include('account.urls')),
]

Sales_accounting/products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('delete/<int:id>', views.product_delete, name='product_delete'),
    path('purchase/', views.purchase_create, name='purchase'),
    path('purchase_list/', views.purchase_list, name='purchase_list'),
    path('group_create/', views.product_group_create, name='group_create'),
    path('overview/', views.overview, name='overview'),
]

Sales_accounting/sales/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.sales_list, name='sales_list'),
    path('create/', views.sale_create, name='sale_create'),
    path('delete/<int:id>', views.sale_delete, name='sale_delete'),

]

Sales_accounting/products/models.py
from django.db import models
from counterparties.models import Counterparty
from account.models import Profile


class ProductGroup(models.Model):
    name = models.CharField(max_length=50)
    created_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='product_groups', null=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    amount = models.IntegerField()
    group = models.ForeignKey(ProductGroup, on_delete=models.CASCADE, related_name='products')
    created_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='products', null=True)

    def __str__(self):
        return f'{self.name}'


class Purchase(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    counterparty = models.ForeignKey(Counterparty, on_delete=models.CASCADE, related_name='purchases')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='purchases')
    purchase_price = models.IntegerField(default=0)
    full_purchase_price = models.IntegerField(default=0)
    amount = models.IntegerField()
    created_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='purchases', null=True)

Sales_accounting/products/forms.py
from django import forms
from .models import Product, Purchase, ProductGroup


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'amount', 'group']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }


class PurchaseCreateForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['counterparty', 'product', 'purchase_price', 'amount', 'full_purchase_price']

        widgets = {
            'counterparty': forms.Select(attrs={'class': 'form-control'}),
            'product': forms.Select(attrs={'class': 'form-control'}),
            'purchase_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'full_purchase_price': forms.HiddenInput(),
        }


class ProductGroupCreateForm(forms.ModelForm):
    class Meta:
        model = ProductGroup
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

Sales_accounting/products/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product, Purchase
from .forms import ProductCreateForm, PurchaseCreateForm, ProductGroupCreateForm
from django.contrib.auth.decorators import login_required
from sales.models import Sale
from django.contrib import messages


# from django.views.generic import


@login_required
def product_list(request):
    products = Product.objects.filter(created_user=request.user.profile)
    return render(request, 'products/product_list.html', {'products': products, 'section': 'products'})


@login_required
def purchase_list(request):
    purchases = Purchase.objects.filter(created_user=request.user.profile)
    return render(request, 'products/purchase_list.html', {'purchases': purchases, 'section': 'purchases'})


def product_detail(request, id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        form = ProductCreateForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
        messages.success(request, 'Changes saved')
        return render(request, 'products/product_detail.html', {'form': form})
    else:
        form = ProductCreateForm(instance=product)
        return render(request, 'products/product_detail.html', {'form': form})


def product_create(request):
    # import pdb
    # pdb.set_trace()
    if request.method == 'POST':
        form = ProductCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_user = request.user.profile
            form.save()
        return redirect('products:product_list')
    else:
        form = ProductCreateForm()
        return render(request, 'products/proudct_create.html', {'form': form})


def product_delete(request, id):
    product_for_delete = Product.objects.get(id=id)
    product_for_delete.delete()
    messages.error(request, 'Product deleted successfully')
    return redirect('products:product_list')


def purchase_create(request):
    if request.method == 'POST':
        form = PurchaseCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            product_amount = form.cleaned_data['amount']
            purchase_price = form.cleaned_data['purchase_price']
            instance.full_purchase_price = product_amount * purchase_price
            product = form.cleaned_data['product']
            product.amount += product_amount
            instance.created_user = request.user.profile
            product.save()
            form.save()
            messages.success(request, 'Purchase created successfully!')
            return redirect('products:purchase_list')
        return render(request, 'products/purchase.html', {'form': form})
    else:
        form = PurchaseCreateForm()
        return render(request, 'products/purchase.html', {'form': form})


def product_group_create(request):
    if request.method == 'POST':
        form = ProductGroupCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_user = request.user.profile
            form.save()
            return redirect('products:product_create')
        return render(request, 'products/product_group_create.html', {'form': form})
    else:
        form = ProductGroupCreateForm()
        return render(request, 'products/product_group_create.html', {'form': form})


def overview(request):
    sum_sales = 0
    sum_purchases = 0
    profit = 0
    if request.method == 'GET':
        all_sales = Sale.objects.filter(created_user=request.user.profile)
        all_purchases = Purchase.objects.filter(created_user=request.user.profile)
        for sale in all_sales:
            sum_sales += sale.final_price
        for pur in all_purchases:
            sum_purchases += pur.full_purchase_price
        profit = sum_sales - sum_purchases
    return render(request, 'products/overview.html', {'profit': profit, 'section': 'overview'})

Sales_accounting/products/templates/products/overview.html
{% extends 'base.html' %}

{% block title %}
    Overview
{% endblock %}

{% block content %}


    <table class="table">
        <thead>
        <tr>
            <th scope="col">Состояние</th>
            <th scope="col">Сумма</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                {% if profit > 0 %}
                    Профит
                {% else %}
                    Убытки
                {% endif %}
            </td>
            <td>{{ profit }}</td>
        </tr>
        </tbody>
    </table>

{% endblock %}

Sales_accounting/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ product.name|capfirst }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
{% endblock %}

Sales_accounting/products/templates/products/product_group_create.html
{% extends 'base.html' %}

{% block title %}
    Product Group create
{% endblock %}

{% block content %}
    <form action="{% url 'products:group_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

Sales_accounting/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %}
    Products
{% endblock %}

{% block content %}
    <p>
        <header>
            <a class="button" href="{% url 'products:product_create' %}">Add new product</a>
            <a class="button" href="{% url 'products:purchase' %}">Add purchase</a>
        </header>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Группа</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <th scope="row">{{ product.id }}</th>
                <td><a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a></td>
                <td>{{ product.price }}</td>
                <td>{{ product.amount }}</td>
                <td>{{ product.group.name }}</td>
                <td scope="col"><a class="button-danger" href="{% url 'products:product_delete' product.id %}">DELETE</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

Sales_accounting/products/templates/products/proudct_create.html
{% extends 'base.html' %}

{% block title %}
    Product create
{% endblock %}

{% block content %}
    <form action="{% url 'products:product_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

Sales_accounting/products/templates/products/purchase.html
{% extends 'base.html' %}

{% block title %}
    Purchase
{% endblock %}

{% block content %}
     <form action="{% url 'products:purchase' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

Sales_accounting/products/templates/products/purchase_list.html
{% extends 'base.html' %}

{% block title %}
    Products
{% endblock %}

{% block content %}
{#    <p>#}
{#        <header>#}
{#            <a class="button" href="{% url 'products:product_create' %}">Add new product</a>#}
{#            <a class="button" href="{% url 'products:purchase' %}">Add purchase</a>#}
{#        </header>#}
{#    </p>#}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Время</th>
            <th scope="col">Контрагент</th>
            <th scope="col">Продукт</th>
            <th scope="col">Сумма</th>
            <th scope="col">Количество</th>
        </tr>
        </thead>
        <tbody>
        {% for purchase in purchases %}
            <tr>
                <th scope="row">{{ purchase.id }}</th>
{#                <td><a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a></td>#}
                <td>{{ purchase.time }}</td>
                <td>{{ purchase.counterparty }}</td>
                <td>{{ purchase.product.name }}</td>
                <td>{{ purchase.full_purchase_price}}</td>
                <td>{{ purchase.amount}}</td>
{#                <td scope="col"><a class="button-danger" href="{% url 'products:product_delete' product.id %}">DELETE</a></td>#}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}