Sales_accounting/Sales_accounting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('account/', include('account.urls')),
]

Sales_accounting/counterparties/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'counterparties'

urlpatterns = [
    path('', views.counterparty_list, name='counterparties_list'),
    path('create/', views.counterparty_create, name='counterparties_create'),

]

Sales_accounting/products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('create/', views.product_create, name='product_create'),
    path('delete/<int:id>', views.product_delete, name='product_delete'),
    path('purchase/', views.purchase_create, name='purchase'),
    path('purchase_list/', views.purchase_list, name='purchase_list'),
    path('group_create/', views.product_group_create, name='group_create'),
    path('overview/', views.overview, name='overview'),
]

Sales_accounting/sales/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.sales_list, name='sales_list'),
    path('create/', views.sale_create, name='sale_create'),
    path('delete/<int:id>', views.sale_delete, name='sale_delete'),

]

Sales_accounting/counterparties/models.py
from django.db import models
from account.models import Profile


class Counterparty(models.Model):
    type_choises = [('suplier', 'Supplier'), ('buyer', 'Buyer')]
    name = models.CharField(max_length=100)
    phone = models.IntegerField()
    email = models.EmailField()
    product_group = models.ManyToManyField('products.ProductGroup')
    balance = models.IntegerField(default=0)
    type = models.CharField(choices=type_choises, max_length=20)
    created_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='counterpartyes', null=True)

    def __str__(self):
        return self.name

Sales_accounting/counterparties/forms.py
from django import forms
from .models import Counterparty


class CounterpartiesForm(forms.ModelForm):
    class Meta:
        model = Counterparty
        fields = ['name', 'phone', 'email', 'product_group', 'type']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'product_group': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
        }

Sales_accounting/counterparties/views.py
from django.shortcuts import render, redirect
from .models import Counterparty
from .forms import CounterpartiesForm
from django.contrib.auth.decorators import login_required


@login_required
def counterparty_list(request):
    cp = Counterparty.objects.filter(created_user=request.user.profile)
    return render(request, 'counterparty/cp_list.html', {'cps': cp, 'section': 'cp'})


def counterparty_create(request):
    if request.method == 'POST':
        form = CounterpartiesForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_user = request.user.profile
            form.save()
            return redirect('counterparties:counterparties_list')
        return render(request, 'counterparty/cp_create.html', {'form': form})
    else:
        form = CounterpartiesForm()
        return render(request, 'counterparty/cp_create.html', {'form': form})

Sales_accounting/counterparties/templates/counterparty/cp_create.html
{% extends 'base.html' %}

{% block title %}
    Counterparty create
{% endblock %}

{% block content %}
    <form action="{% url 'counterparties:counterparties_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

Sales_accounting/counterparties/templates/counterparty/cp_list.html
{% extends 'base.html' %}

{% block title %}
    Counterparties
{% endblock %}

{% block content %}
    <p>
        <header>
            <a class="button" href="{% url 'counterparties:counterparties_create' %}">Add new counterparty</a>
        </header>
    </p>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Телефон</th>
            <th scope="col">E-mail</th>
            <th scope="col">Баланс</th>
            <th scope="col">Тип</th>
        </tr>
        </thead>
        <tbody>
        {% for cp in cps %}
            <tr>
                <th scope="row">{{ cp.id }}</th>
                {#                <td><a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a></td>#}
                <td>{{ cp.name }}</td>
                <td>{{ cp.phone }}</td>
                <td>{{ cp.email }}</td>
                <td>{{ cp.balance }}</td>
                <td>{{ cp.type|title }}</td>
                {#                <td scope="col"><a class="button-danger" href="{% url 'products:product_delete' product.id %}">DELETE</a></td>#}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}